name: local-rating CI (pull request)

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    # https://www.scala-sbt.org/1.x/docs/GitHub-Actions-with-sbt.html#Custom+JVM+options
    env:
      # define Java options for both official sbt and sbt-extras
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS:  -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
#    - name: Build functions
#      run: sbt functionsBackend/assembly
    - name: Test webapp
      run: sbt test
      working-directory: ./app
    - name: Build webapp
      run: sbt prod
      working-directory: ./app
